### ISSUE TITLE
Loading config from file not working right

### ISSUE THREAD

**Issue by jmunson** [alecthomas/gometalinter#173]
It seems like time parsing in --deadline does not work
```
❯ gometalinter @.gometalinterrc ./...        
gometalinter: error: time: invalid duration "15m", try --help

❯ cat .gometalinterrc 
--vendor
--vendored-linters
-E gofmt-s
-E goimports
-E misspell
-D dupl
-D varcheck
-D structcheck
-D aligncheck
--sort=severity
--exclude="_test"
--deadline="15m"
```

Additionally it seems like theres an issue with the order of the cmdline arguments given

```
❯ gometalinter ./pkg/filestore @.gometalinterrc      
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x615560, 0xc420014190)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
gopkg.in/alecthomas/kingpin%2ev2.(*ParseContext).Next(0xc4200b2120, 0x0)
        /home/jmunson/go/src/gopkg.in/alecthomas/kingpin.v2/parser.go:217 +0xc64
gopkg.in/alecthomas/kingpin%2ev2.(*ParseContext).Peek(0xc4200b2120, 0xc420011d80)
        /home/jmunson/go/src/gopkg.in/alecthomas/kingpin.v2/parser.go:229 +0x60
gopkg.in/alecthomas/kingpin%2ev2.(*ParseContext).EOL(0xc4200b2120, 0xc420011d60)
        /home/jmunson/go/src/gopkg.in/alecthomas/kingpin.v2/parser.go:152 +0x2b
gopkg.in/alecthomas/kingpin%2ev2.parse(0xc4200b2120, 0xc4200d8000, 0xc42000def0, 0x0)
        /home/jmunson/go/src/gopkg.in/alecthomas/kingpin.v2/parser.go:292 +0xa2
gopkg.in/alecthomas/kingpin%2ev2.(*Application).parseContext(0xc4200d8000, 0x0, 0xc42000c400, 0x2, 0x2, 0xc42004dd98, 0x490a41, 0xc420106fa6)
        /home/jmunson/go/src/gopkg.in/alecthomas/kingpin.v2/app.go:173 +0x214
gopkg.in/alecthomas/kingpin%2ev2.(*Application).ParseContext(0xc4200d8000, 0xc42000c400, 0x2, 0x2, 0x0, 0xc42004dd70, 0x51ae82)
        /home/jmunson/go/src/gopkg.in/alecthomas/kingpin.v2/app.go:165 +0x4e
gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc4200d8000, 0xc42000c400, 0x2, 0x2, 0x1000, 0xc420107000, 0xfa7, 0xfa7)
        /home/jmunson/go/src/gopkg.in/alecthomas/kingpin.v2/app.go:185 +0x67
gopkg.in/alecthomas/kingpin%2ev2.Parse(0x65d76c, 0x8c)
        /home/jmunson/go/src/gopkg.in/alecthomas/kingpin.v2/global.go:37 +0x7e
main.main()
        /home/jmunson/go/src/github.com/alecthomas/gometalinter/main.go:329 +0x191
```
If I specify a second valid path after the @.gometalinterrc, it works fine and scans both of them

If I specify just a path after the @.gometalinterrc without a path before it,  it runs gometalinter on the *.go files in the current directory and does not utilize the path given

**Comment by alecthomas** [comment]
Quotes should not be used in the file. Quotes are utilised by the shell. That second one is definitely a bug though, I'll move it over to kingpin.
