### ISSUE TITLE
Backward incompatibility after change 2254d21c95bb71c5380434accf030201e46d5aca

### ISSUE THREAD

**Issue by ggeorgiev** [alecthomas/gometalinter#196]
after the mentioned in the title change the command: `gometalinter --linter='errcheck:errcheck -tags lint -abspath {path}:PATH:LINE:COL:MESSAGE'` that used to work - no longer works with panic message:
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x26c600, 0xc4200140f0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
main.LinterFromName(0x2b4491, 0xa, 0xc420118900)
	/Users/george/golang/src/github.com/alecthomas/gometalinter/main.go:55 +0x602
main.lintersFromFlags(0x0)
	/Users/george/golang/src/github.com/alecthomas/gometalinter/main.go:855 +0x9e
main.main()
	/Users/george/golang/src/github.com/alecthomas/gometalinter/main.go:444 +0x268

**Comment by ggeorgiev** [comment]
thanks
