### ISSUE TITLE
Error: "slice bounds out of range"

### ISSUE THREAD

**Issue by willfaught** [alecthomas/gometalinter#265]
Command in repo root:

```
$ gometalinter --cyclo-over 50 --enable-all --disable gotype --disable test --disable testify --dupl-threshold 100 --line-length 200 --linter='errcheck:errcheck -ignorepkg github.com/go-kit/kit/log {path}:PATH:LINE:MESSAGE' --skip pb --tests --vendor --deadline 30s --fast ./...
```

Output:

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.disableAction(0xc420111b00, 0xc420160240, 0x0, 0x0)
	/Users/will.faught/Developer/go/src/github.com/alecthomas/gometalinter/main.go:194 +0x237
github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin%2ev3-unstable.(*actionMixin).applyActions(0xc420137680, 0xc420111b00, 0xc420160240, 0x0, 0x0)
	/Users/will.faught/Developer/go/src/github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin.v3-unstable/actions.go:31 +0x62
github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin%2ev3-unstable.(*Application).applyActions(0xc420114b60, 0xc420160240, 0x0, 0x0)
	/Users/will.faught/Developer/go/src/github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin.v3-unstable/app.go:619 +0xe6
github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin%2ev3-unstable.(*Application).execute(0xc420114b60, 0xc420160240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1064b72, 0x13a5410)
	/Users/will.faught/Developer/go/src/github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin.v3-unstable/app.go:347 +0x64
github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin%2ev3-unstable.(*Application).Parse(0xc420114b60, 0xc420010190, 0x16, 0x17, 0x1500, 0xc420120600, 0x1039, 0x1039)
	/Users/will.faught/Developer/go/src/github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin.v3-unstable/app.go:200 +0x202
github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin%2ev3-unstable.Parse(0x128a00b, 0x90)
	/Users/will.faught/Developer/go/src/github.com/alecthomas/gometalinter/vendor/gopkg.in/alecthomas/kingpin.v3-unstable/global.go:31 +0x78
main.main()
	/Users/will.faught/Developer/go/src/github.com/alecthomas/gometalinter/main.go:300 +0x174
make: *** [lint] Error 2
```

**Comment by alecthomas** [comment]
Interestingly, I cannot replicate this. Are you running from master?

**Comment by alecthomas** [comment]
Disregard that, found the bug.
