### ISSUE TITLE
concurrent map access

### ISSUE THREAD

**Issue by hollow** [alecthomas/gometalinter#306]
The latest gometalinter crashes very frequently with concurrent map access violations, e.g.:

```
fatal error: concurrent map iteration and map write
goroutine 1 [running]:
runtime.throw(0x68baff, 0x26)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/panic.go:596 +0x95 fp=0xc420051958 sp=0xc420051938
runtime.mapiternext(0xc420051ab0)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/hashmap.go:737 +0x7ee fp=0xc420051a08 sp=0xc420051958
main.Vars.Replace(0xc420018450, 0xc420162fa0, 0xb, 0xc420051b68, 0x41e302)
	/home/travis/gopath/src/github.com/alecthomas/gometalinter/main.go:268 +0x2f6 fp=0xc420051b20 sp=0xc420051a08
main.(*linterState).Partitions(0xc4213f8280, 0xc4212817a0, 0xc4201d2d80, 0xc4200f9d10, 0xc4200e78a0, 0xc4201c69c0)
	/home/travis/gopath/src/github.com/alecthomas/gometalinter/main.go:659 +0x5c fp=0xc420051c48 sp=0xc420051b20
main.runLinters(0xc420180330, 0xc420170420, 0x1, 0x1, 0x20, 0x0, 0x0, 0x1, 0x1)
	/home/travis/gopath/src/github.com/alecthomas/gometalinter/main.go:442 +0xaa4 fp=0xc420051e68 sp=0xc420051c48
main.main()
	/home/travis/gopath/src/github.com/alecthomas/gometalinter/main.go:307 +0x29d fp=0xc420051f88 sp=0xc420051e68
runtime.main()
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/proc.go:185 +0x20a fp=0xc420051fe0 sp=0xc420051f88
runtime.goexit()
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420051fe8 sp=0xc420051fe0
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/asm_amd64.s:2197 +0x1

```

**Comment by alecthomas** [comment]
Please try latest master.

**Comment by dnephin** [comment]
Thanks for fixing this bug. I missed that there was still one more place where `Vars` is modified in `processOutput()`
